# Generated by Django 3.2.12 on 2022-02-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMI_NLP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top3Predition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_texte1', models.CharField(max_length=2000)),
                ('result_texte2', models.CharField(max_length=2000)),
                ('result_texte3', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Top3Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text1', models.CharField(max_length=2000)),
                ('result_text2', models.CharField(max_length=2000)),
                ('result_text3', models.CharField(max_length=2000)),
            ],
        ),
    ]
